#!/usr/bin/env node

/**
 * Memory Bridge: Preflight Context Generator
 * 
 * Reads vault/ and creates CONTEXT.md for coding agents.
 * This ensures coding agents have access to past decisions, patterns, and architecture.
 * 
 * Usage:
 *   node preflight-context.js --task "Build auth middleware" --workdir ./my-project
 * 
 * Outputs:
 *   ./my-project/CONTEXT.md — agent reads this automatically
 */

const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

// Parse CLI args
const args = require('minimist')(process.argv.slice(2));
const taskDescription = args.task || args.t || 'Unspecified task';
const workdir = args.workdir || args.w || process.cwd();

const vaultRoot = path.join(process.env.WORKSPACE || path.join(process.env.HOME, '.openclaw/workspace'), 'vault');
const contextFile = path.join(workdir, 'CONTEXT.md');

console.log(`[Memory Bridge] Generating context for: "${taskDescription}"`);
console.log(`[Memory Bridge] Vault root: ${vaultRoot}`);
console.log(`[Memory Bridge] Output: ${contextFile}`);

/**
 * Search vault for relevant files based on task keywords
 */
function findRelevantNotes(keywords) {
  const relevant = [];
  
  try {
    // Get all markdown files from vault/01_thinking (MOCs) and vault/02_reference
    const dirs = [
      path.join(vaultRoot, '01_thinking'),
      path.join(vaultRoot, '02_reference')
    ];
    
    for (const dir of dirs) {
      if (!fs.existsSync(dir)) continue;
      
      const files = fs.readdirSync(dir).filter(f => f.endsWith('.md'));
      for (const file of files) {
        const filePath = path.join(dir, file);
        const content = fs.readFileSync(filePath, 'utf-8');
        
        // Simple keyword matching (in production, use proper vector search)
        const matches = keywords.some(kw => 
          file.toLowerCase().includes(kw.toLowerCase()) ||
          content.toLowerCase().includes(kw.toLowerCase())
        );
        
        if (matches) {
          relevant.push({
            filename: file,
            path: filePath,
            preview: content.split('\n').slice(0, 10).join('\n')
          });
        }
      }
    }
  } catch (e) {
    console.warn(`[Memory Bridge] Warning: Could not scan vault: ${e.message}`);
  }
  
  return relevant;
}

/**
 * Read recent learnings
 */
function getRecentLearnings() {
  const learningsDir = path.join(vaultRoot, '.learnings');
  const learnings = { hot: [], errors: [], corrections: [] };
  
  try {
    if (fs.existsSync(path.join(learningsDir, 'HOT.md'))) {
      learnings.hot = fs.readFileSync(path.join(learningsDir, 'HOT.md'), 'utf-8')
        .split('\n').slice(0, 10).join('\n');
    }
    if (fs.existsSync(path.join(learningsDir, 'ERRORS.md'))) {
      learnings.errors = fs.readFileSync(path.join(learningsDir, 'ERRORS.md'), 'utf-8')
        .split('\n').slice(0, 10).join('\n');
    }
    if (fs.existsSync(path.join(learningsDir, 'corrections.md'))) {
      learnings.corrections = fs.readFileSync(path.join(learningsDir, 'corrections.md'), 'utf-8')
        .split('\n').slice(0, 10).join('\n');
    }
  } catch (e) {
    console.warn(`[Memory Bridge] Warning: Could not read learnings: ${e.message}`);
  }
  
  return learnings;
}

/**
 * Generate CONTEXT.md
 */
function generateContext() {
  const keywords = taskDescription.split(' ').filter(w => w.length > 3);
  const relevant = findRelevantNotes(keywords);
  const learnings = getRecentLearnings();
  
  let context = `# Task Context — ${taskDescription}

Generated by Memory Bridge at ${new Date().toISOString()}

## Task Summary
${taskDescription}

## Relevant Vault Notes
This agent has access to the following vault documents related to this task:

`;
  
  if (relevant.length > 0) {
    for (const note of relevant.slice(0, 5)) {
      context += `### ${note.filename}
\`\`\`
${note.preview}
\`\`\`

`;
    }
  } else {
    context += `(No directly relevant notes found in vault. Use vault/.learnings/ for recent patterns.)\n\n`;
  }
  
  context += `## Recent Learnings & Patterns

### Hot Insights (Last Session)
\`\`\`
${learnings.hot || '(None recorded)'}
\`\`\`

### Recent Errors
\`\`\`
${learnings.errors || '(None recorded)'}
\`\`\`

### Corrections & Feedback
\`\`\`
${learnings.corrections || '(None recorded)'}
\`\`\`

## Instructions for Coding Agent
1. Read this CONTEXT.md first
2. Review linked vault notes if applicable
3. Implement the task following any patterns documented in vault/01_thinking/
4. After completion, update vault/.learnings/HOT.md with any new discoveries

---
This file is auto-generated. Do not edit manually.
`;
  
  return context;
}

// Write context file
try {
  const context = generateContext();
  fs.mkdirSync(workdir, { recursive: true });
  fs.writeFileSync(contextFile, context, 'utf-8');
  console.log(`[Memory Bridge] ✅ Context written to ${contextFile}`);
  console.log(`[Memory Bridge] Size: ${context.length} bytes`);
} catch (e) {
  console.error(`[Memory Bridge] ❌ Failed to write context: ${e.message}`);
  process.exit(1);
}
